name = "onramp"
main = "src/index.ts"
compatibility_date = "2022-09-22"
node_compat = true

[env.development.vars]
STRIPE_SECRET = ""
SIGNING_SECRET = ""
HASURA_URL = "http://localhost:8112/v1/graphql"
JWT=""