# gh-pages branch is deployed on every commit to update the service-worker
# the process creates a new folder for every commit hash, which leads to
# thousands of folders that are never used
# This purges the old folders. The script lives in gh-pages branch called check-for-old-folders.sh

name: Purge old service worker folders from gh-pages
on:
  workflow_dispatch:
    inputs:
      beforeDate:
        description: "Before Date (YYYY-MM-DD)"
        type: string
        default: "2023-02-03"
      afterDate:
        description: "After Date (YYYY-MM-DD)"
        type: string
        default: "2023-01-14"
  schedule:
    - cron: 0 0 * * * # Run every day at midnight (12am)
  push:
    branches:
      - master
      - gh-pages

jobs:
  purge:
    name: Purge old service worker folders from gh-pages
    runs-on: ubuntu-latest
    steps:
      - run: git config --global user.email "github-actions[bot]@users.noreply.github.com" && git config --global user.name "github-actions"
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 100
      - run: bash ./check-for-old-folders.sh ${{ inputs.beforeDate }} ${{ inputs.afterDate }}
        shell: bash
